(in-package :honepad-user)

(defclass gpu ()
  ((gpu-id :initarg :gpu-id :accessor gpu-id)
   (mem :initarg :mem :accessor gpu-mem)
   (job-id :initform nil :accessor gpu-job-id)))

(defclass job ()
  ((job-id :initarg :job-id :accessor job-id)
   (mem :initarg :mem :accessor job-mem)
   (seq :initarg :seq :accessor job-seq)
   (priority :initform 0 :accessor job-priority)
   (state :initform "queued" :accessor job-state)
   (gpu-id :initform nil :accessor job-gpu-id)))

(defclass simulation ()
  ((gpus :initform (make-hash-table :test 'equal) :accessor sim-gpus)
   (gpu-order :initform nil :accessor sim-gpu-order)
   (jobs :initform (make-hash-table :test 'equal) :accessor sim-jobs)
   (next-seq :initform 0 :accessor sim-next-seq)))

(defun place (job gpu)
  (setf (job-state job) "running")
  (setf (job-gpu-id job) (gpu-id gpu))
  (setf (gpu-job-id gpu) (job-id job)))

(defmethod add_gpu ((sim simulation) gpu-id mem)
  (when (<= mem 0)
    (return-from add_gpu "invalid_request"))
  (when (gethash gpu-id (sim-gpus sim))
    (return-from add_gpu "false"))
  (setf (gethash gpu-id (sim-gpus sim))
        (make-instance 'gpu :gpu-id gpu-id :mem mem))
  (setf (sim-gpu-order sim) (append (sim-gpu-order sim) (list gpu-id)))
  "true")

(defmethod submit_job ((sim simulation) job-id mem)
  (when (<= mem 0)
    (return-from submit_job "invalid_request"))
  (when (gethash job-id (sim-jobs sim))
    (return-from submit_job "false"))
  (setf (gethash job-id (sim-jobs sim))
        (make-instance 'job :job-id job-id :mem mem :seq (sim-next-seq sim)))
  (incf (sim-next-seq sim))
  "true")

(defmethod status ((sim simulation) job-id)
  (let ((job (gethash job-id (sim-jobs sim))))
    (if job (job-state job) "")))

(defmethod assign ((sim simulation))
  (let ((queued nil))
    (maphash (lambda (id job)
               (declare (ignore id))
               (when (string= (job-state job) "queued")
                 (push job queued)))
             (sim-jobs sim))
    (setf queued
          (sort queued
                (lambda (a b)
                  (or (> (job-priority a) (job-priority b))
                      (and (= (job-priority a) (job-priority b))
                           (< (job-seq a) (job-seq b)))))))
    (dolist (job queued)
      (dolist (gpu-id (sim-gpu-order sim))
        (let ((gpu (gethash gpu-id (sim-gpus sim))))
          (when (and (null (gpu-job-id gpu)) (>= (gpu-mem gpu) (job-mem job)))
            (place job gpu)
            (return-from assign (job-id job))))))
    ""))

(defmethod complete ((sim simulation) job-id)
  (let ((job (gethash job-id (sim-jobs sim))))
    (when (or (null job)
              (not (string= (job-state job) "running"))
              (null (job-gpu-id job)))
      (return-from complete "invalid_request"))
    (setf (gpu-job-id (gethash (job-gpu-id job) (sim-gpus sim))) nil)
    (setf (job-gpu-id job) nil)
    (setf (job-state job) "done")
    "true"))

(defmethod cancel ((sim simulation) job-id)
  (let ((job (gethash job-id (sim-jobs sim))))
    (when (or (null job) (string= (job-state job) "done"))
      (return-from cancel "invalid_request"))
    (when (and (string= (job-state job) "running") (job-gpu-id job))
      (setf (gpu-job-id (gethash (job-gpu-id job) (sim-gpus sim))) nil))
    (remhash job-id (sim-jobs sim))
    (when (string= (job-state job) "running")
      (assign sim))
    "true"))

(defmethod set_priority ((sim simulation) job-id priority)
  (let ((job (gethash job-id (sim-jobs sim))))
    (when (or (null job) (not (string= (job-state job) "queued")))
      (return-from set_priority "invalid_request"))
    (setf (job-priority job) priority)
    "true"))
