{ InMemoryDatabase stub. Fill methods from the problem spec.
{ set(key, field, value)
{ get(key, field)
{ delete(key, field)
{ scan(key)
{ scan_by_prefix(key, prefix)
{ set_at(key, field, value, timestamp)
{ set_at_with_ttl(key, field, value, timestamp, ttl)
{ delete_at(key, field, timestamp)
{ get_at(key, field, timestamp)
{ scan_at(key, timestamp)
{ scan_by_prefix_at(key, prefix, timestamp)
{ backup(timestamp)
{ restore(timestamp, timestamp_to_restore)
