(in-package :honepad-user)

(defclass stored-file ()
  ((name :initarg :name :accessor file-name)
   (size :initarg :size :accessor file-size)
   (owner :initarg :owner :accessor file-owner)))

(defclass simulation ()
  ((files :initform (make-hash-table :test 'equal) :accessor sim-files)
   (file-names :initform nil :accessor sim-file-names)
   (capacity :initform (let ((h (make-hash-table :test 'equal)))
                         (setf (gethash "admin" h) nil)
                         h)
             :accessor sim-capacity)
   (backups :initform (make-hash-table :test 'equal) :accessor sim-backups)))

(defun file-used (sim user-id)
  (let ((total 0))
    (maphash (lambda (name item)
               (declare (ignore name))
               (when (string= (file-owner item) user-id)
                 (incf total (file-size item))))
             (sim-files sim))
    total))

(defun file-remaining (sim user-id)
  (multiple-value-bind (cap present) (gethash user-id (sim-capacity sim))
    (declare (ignore present))
    (if (null cap)
        nil
        (- cap (file-used sim user-id)))))

(defun add-stored-file (sim name size owner)
  (setf (gethash name (sim-files sim))
        (make-instance 'stored-file :name name :size size :owner owner))
  (setf (sim-file-names sim) (append (sim-file-names sim) (list name))))

(defun remove-stored-file (sim name)
  (let ((item (gethash name (sim-files sim))))
    (remhash name (sim-files sim))
    (setf (sim-file-names sim) (remove name (sim-file-names sim) :test #'string=))
    item))

(defmethod add_file ((sim simulation) name size)
  (when (gethash name (sim-files sim))
    (return-from add_file "false"))
  (add-stored-file sim name size "admin")
  "true")

(defmethod get_file_size ((sim simulation) name)
  (let ((item (gethash name (sim-files sim))))
    (if item (princ-to-string (file-size item)) "")))

(defmethod delete_file ((sim simulation) name)
  (let ((item (remove-stored-file sim name)))
    (if item (princ-to-string (file-size item)) "")))

(defmethod get_n_largest ((sim simulation) prefix n)
  (let ((matched nil))
    (maphash
     (lambda (name item)
       (declare (ignore name))
       (when (and (>= (length (file-name item)) (length prefix))
                  (string= (file-name item) prefix :end1 (length prefix)))
         (push item matched)))
     (sim-files sim))
    (setf matched
          (sort matched
                (lambda (a b)
                  (cond
                    ((> (file-size a) (file-size b)) t)
                    ((< (file-size a) (file-size b)) nil)
                    (t (string< (file-name a) (file-name b)))))))
    (let ((count (min n (length matched))))
      (with-output-to-string (out)
        (loop for item in matched
              for i from 0 below count
              do (when (> i 0) (write-string ", " out))
                 (format out "~a(~a)" (file-name item) (file-size item)))))))

(defmethod add_user ((sim simulation) user_id capacity)
  (when (nth-value 1 (gethash user_id (sim-capacity sim)))
    (return-from add_user "false"))
  (setf (gethash user_id (sim-capacity sim)) capacity)
  "true")

(defmethod add_file_by ((sim simulation) user_id name size)
  (unless (nth-value 1 (gethash user_id (sim-capacity sim)))
    (return-from add_file_by ""))
  (when (gethash name (sim-files sim))
    (return-from add_file_by ""))
  (let ((left (file-remaining sim user_id)))
    (when (and left (> size left))
      (return-from add_file_by "")))
  (add-stored-file sim name size user_id)
  (let ((left (file-remaining sim user_id)))
    (if left (princ-to-string left) "")))

(defmethod merge_user ((sim simulation) user_id1 user_id2)
  (when (string= user_id1 user_id2)
    (return-from merge_user ""))
  (unless (and (nth-value 1 (gethash user_id1 (sim-capacity sim)))
               (nth-value 1 (gethash user_id2 (sim-capacity sim))))
    (return-from merge_user ""))
  (let ((cap1 (gethash user_id1 (sim-capacity sim)))
        (cap2 (gethash user_id2 (sim-capacity sim))))
    (when (or (null cap1) (null cap2))
      (return-from merge_user ""))
    (setf (gethash user_id1 (sim-capacity sim)) (+ cap1 cap2))
    (maphash (lambda (name item)
               (declare (ignore name))
               (when (string= (file-owner item) user_id2)
                 (setf (file-owner item) user_id1)))
             (sim-files sim))
    (remhash user_id2 (sim-capacity sim))
    (remhash user_id2 (sim-backups sim))
    (let ((left (file-remaining sim user_id1)))
      (if left (princ-to-string left) ""))))

(defmethod backup_user ((sim simulation) user_id)
  (unless (nth-value 1 (gethash user_id (sim-capacity sim)))
    (return-from backup_user ""))
  (let ((snapshot nil))
    (dolist (name (sim-file-names sim))
      (let ((item (gethash name (sim-files sim))))
        (when (and item (string= (file-owner item) user_id))
          (setf snapshot (append snapshot (list (cons name (file-size item))))))))
    (setf (gethash user_id (sim-backups sim)) snapshot)
    (princ-to-string (length snapshot))))

(defmethod restore_user ((sim simulation) user_id)
  (unless (nth-value 1 (gethash user_id (sim-capacity sim)))
    (return-from restore_user ""))
  (dolist (name (copy-list (sim-file-names sim)))
    (let ((item (gethash name (sim-files sim))))
      (when (and item (string= (file-owner item) user_id))
        (remove-stored-file sim name))))
  (let ((snapshot (gethash user_id (sim-backups sim))))
    (unless snapshot
      (return-from restore_user "0"))
    (let ((restored 0))
      (dolist (pair snapshot)
        (let ((name (car pair))
              (size (cdr pair)))
          (unless (gethash name (sim-files sim))
            (let ((left (file-remaining sim user_id)))
              (unless (and left (> size left))
                (add-stored-file sim name size user_id)
                (incf restored))))))
      (princ-to-string restored))))
