(in-package :honepad-user)

(shadow 'length)

(defclass simulation ()
  ((buf :initform "" :accessor sim-buf)
   (pos :initform 0 :accessor sim-pos)
   (undo-stack :initform nil :accessor sim-undo)
   (redo-stack :initform nil :accessor sim-redo)
   (sel :initform nil :accessor sim-sel)
   (clip :initform "" :accessor sim-clip)))

(defun push-snap (sim)
  (push (cons (sim-buf sim) (sim-pos sim)) (sim-undo sim))
  (setf (sim-redo sim) nil)
  (setf (sim-sel sim) nil))

(defmethod insert ((sim simulation) pos text)
  (when (or (< pos 0) (> pos (cl:length (sim-buf sim))))
    (return-from insert "invalid_request"))
  (push-snap sim)
  (setf (sim-buf sim)
        (concatenate 'string
                     (subseq (sim-buf sim) 0 pos)
                     text
                     (subseq (sim-buf sim) pos)))
  (princ-to-string (cl:length (sim-buf sim))))

(defmethod erase ((sim simulation) pos n)
  (when (or (<= n 0) (< pos 0) (> (+ pos n) (cl:length (sim-buf sim))))
    (return-from erase "invalid_request"))
  (push-snap sim)
  (let ((deleted (subseq (sim-buf sim) pos (+ pos n))))
    (setf (sim-buf sim)
          (concatenate 'string
                       (subseq (sim-buf sim) 0 pos)
                       (subseq (sim-buf sim) (+ pos n))))
    (when (> (sim-pos sim) (cl:length (sim-buf sim)))
      (setf (sim-pos sim) (cl:length (sim-buf sim))))
    deleted))

(defmethod get_text ((sim simulation))
  (sim-buf sim))

(defmethod length ((sim simulation))
  (princ-to-string (cl:length (sim-buf sim))))

(defmethod move ((sim simulation) pos)
  (when (or (< pos 0) (> pos (cl:length (sim-buf sim))))
    (return-from move "invalid_request"))
  (setf (sim-pos sim) pos)
  "true")

(defmethod type_text ((sim simulation) text)
  (push-snap sim)
  (let ((at (sim-pos sim)))
    (setf (sim-buf sim)
          (concatenate 'string
                       (subseq (sim-buf sim) 0 at)
                       text
                       (subseq (sim-buf sim) at)))
    (setf (sim-pos sim) (+ at (cl:length text)))
    (princ-to-string (cl:length (sim-buf sim)))))

(defmethod cursor ((sim simulation))
  (princ-to-string (sim-pos sim)))

(defmethod undo ((sim simulation))
  (unless (sim-undo sim)
    (return-from undo "false"))
  (push (cons (sim-buf sim) (sim-pos sim)) (sim-redo sim))
  (let ((snap (pop (sim-undo sim))))
    (setf (sim-buf sim) (car snap))
    (setf (sim-pos sim) (cdr snap)))
  (setf (sim-sel sim) nil)
  "true")

(defmethod redo ((sim simulation))
  (unless (sim-redo sim)
    (return-from redo "false"))
  (push (cons (sim-buf sim) (sim-pos sim)) (sim-undo sim))
  (let ((snap (pop (sim-redo sim))))
    (setf (sim-buf sim) (car snap))
    (setf (sim-pos sim) (cdr snap)))
  (setf (sim-sel sim) nil)
  "true")

(defmethod select ((sim simulation) start end)
  (when (or (< start 0) (< end 0) (> start end) (> end (cl:length (sim-buf sim))))
    (return-from select "invalid_request"))
  (setf (sim-sel sim) (cons start end))
  "true")

(defmethod cut ((sim simulation))
  (let ((sel (sim-sel sim)))
    (when (or (null sel) (= (car sel) (cdr sel)))
      (return-from cut "invalid_request"))
    (let* ((start (car sel))
           (end (cdr sel))
           (text (subseq (sim-buf sim) start end)))
      (setf (sim-buf sim)
            (concatenate 'string
                         (subseq (sim-buf sim) 0 start)
                         (subseq (sim-buf sim) end)))
      (setf (sim-clip sim) text)
      (setf (sim-pos sim) start)
      (setf (sim-sel sim) nil)
      text)))

(defmethod copy_sel ((sim simulation))
  (let ((sel (sim-sel sim)))
    (when (or (null sel) (= (car sel) (cdr sel)))
      (return-from copy_sel "invalid_request"))
    (setf (sim-clip sim) (subseq (sim-buf sim) (car sel) (cdr sel)))
    (sim-clip sim)))

(defmethod paste ((sim simulation))
  (when (string= (sim-clip sim) "")
    (return-from paste "invalid_request"))
  (let ((at (sim-pos sim)))
    (setf (sim-buf sim)
          (concatenate 'string
                       (subseq (sim-buf sim) 0 at)
                       (sim-clip sim)
                       (subseq (sim-buf sim) at)))
    (setf (sim-pos sim) (+ at (cl:length (sim-clip sim))))
    (princ-to-string (cl:length (sim-buf sim)))))
