// Simulation stub. Fill methods from the problem spec.
// insert(pos, text)
// erase(pos, n)
// get_text()
// length()
// move(pos)
// type_text(text)
// cursor()
// undo()
// redo()
// select(start, end)
// cut()
// copy_sel()
// paste()
