(in-package :honepad-user)

(defclass backend ()
  ((backend-id :initarg :backend-id :accessor backend-id)
   (health :initform t :accessor backend-health)
   (weight :initform 1 :accessor backend-weight)
   (inflight :initform 0 :accessor backend-inflight)))

(defclass simulation ()
  ((backends :initform nil :accessor sim-backends)
   (by-id :initform (make-hash-table :test 'equal) :accessor sim-by-id)
   (cursor :initform 0 :accessor sim-cursor)
   (sticky-map :initform (make-hash-table :test 'equal) :accessor sim-sticky-map)
   (use-least :initform nil :accessor sim-use-least)))

(defun reset-cycle (sim)
  (setf (sim-cursor sim) 0)
  (setf (sim-use-least sim) nil)
  (dolist (item (sim-backends sim))
    (setf (backend-inflight item) 0)))

(defun tickets (items)
  (let ((out nil))
    (dolist (item items)
      (dotimes (_ (backend-weight item))
        (push item out)))
    (nreverse out)))

(defun pick (sim)
  (let ((healthy (remove-if-not #'backend-health (sim-backends sim))))
    (when healthy
      (let ((pool healthy))
        (when (sim-use-least sim)
          (let ((least (reduce #'min healthy :key #'backend-inflight)))
            (setf pool (remove-if-not (lambda (item)
                                        (= (backend-inflight item) least))
                                      healthy))))
        (let ((tix (tickets pool)))
          (when tix
            (let ((chosen (nth (mod (sim-cursor sim) (length tix)) tix)))
              (incf (sim-cursor sim))
              chosen)))))))

(defun take (sim)
  (let ((item (pick sim)))
    (if (null item)
        ""
        (progn
          (incf (backend-inflight item))
          (backend-id item)))))

(defmethod add_backend ((sim simulation) backend-id)
  (when (gethash backend-id (sim-by-id sim))
    (return-from add_backend "false"))
  (let ((item (make-instance 'backend :backend-id backend-id)))
    (setf (sim-backends sim) (append (sim-backends sim) (list item)))
    (setf (gethash backend-id (sim-by-id sim)) item)
    "true"))

(defmethod set_health ((sim simulation) backend-id flag)
  (let ((item (gethash backend-id (sim-by-id sim))))
    (when (or (null item) (not (member flag '(0 1))))
      (return-from set_health "invalid_request"))
    (setf (backend-health item) (= flag 1))
    (reset-cycle sim)
    "true"))

(defmethod set_weight ((sim simulation) backend-id weight)
  (let ((item (gethash backend-id (sim-by-id sim))))
    (when (or (null item) (<= weight 0))
      (return-from set_weight "invalid_request"))
    (setf (backend-weight item) weight)
    (reset-cycle sim)
    "true"))

(defmethod route ((sim simulation))
  (take sim))

(defmethod sticky ((sim simulation) client-id)
  (let* ((bound (gethash client-id (sim-sticky-map sim)))
         (item (and bound (gethash bound (sim-by-id sim)))))
    (if (and item (backend-health item))
        (progn
          (incf (backend-inflight item))
          (backend-id item))
        (let ((chosen (take sim)))
          (when (string/= chosen "")
            (setf (gethash client-id (sim-sticky-map sim)) chosen))
          chosen))))

(defmethod done ((sim simulation) backend-id)
  (let ((item (gethash backend-id (sim-by-id sim))))
    (when (or (null item) (<= (backend-inflight item) 0))
      (return-from done "invalid_request"))
    (decf (backend-inflight item))
    (setf (sim-use-least sim) t)
    "true"))
