(in-package :honepad-user)

(defparameter *cashback-delay* (* 24 60 60 1000))

(defclass account ()
  ((account-id :initarg :account-id :accessor account-id)
   (balance :initform 0 :accessor account-balance)
   (outgoing :initform 0 :accessor account-outgoing)
   (payments :initform (make-hash-table :test 'equal) :accessor account-payments)
   (created-at :initarg :created-at :accessor account-created-at)
   (balance-history :initarg :balance-history :accessor account-balance-history)))

(defun make-account (account-id created-at)
  (make-instance 'account
                 :account-id account-id
                 :created-at created-at
                 :balance-history (list (cons created-at 0))))

(defun record-balance (account timestamp)
  (setf (account-balance-history account)
        (append (account-balance-history account)
                (list (cons timestamp (account-balance account))))))

(defun deposit-account (account amount)
  (incf (account-balance account) amount)
  (account-balance account))

(defun withdraw-account (account amount)
  (when (< (account-balance account) amount)
    (return-from withdraw-account :false))
  (decf (account-balance account) amount)
  (incf (account-outgoing account) amount)
  t)

(defun get-balance-at (account time-at)
  (when (< time-at (account-created-at account))
    (return-from get-balance-at nil))
  (let ((result nil))
    (dolist (row (account-balance-history account) result)
      (if (<= (car row) time-at)
          (setf result (cdr row))
          (return result)))))

(defclass simulation ()
  ((accounts :initform (make-hash-table :test 'equal) :accessor sim-accounts)
   (payment-counter :initform 0 :accessor sim-payment-counter)
   (pending-cashbacks :initform nil :accessor sim-pending)))

(defun process-cashbacks (sim timestamp)
  (loop while (and (sim-pending sim)
                   (<= (first (first (sim-pending sim))) timestamp))
        do (let* ((row (pop (sim-pending sim)))
                  (cb-timestamp (first row))
                  (account-id (second row))
                  (amount (third row))
                  (payment-id (fourth row))
                  (account (gethash account-id (sim-accounts sim))))
             (when account
               (deposit-account account amount)
               (setf (gethash payment-id (account-payments account))
                     "CASHBACK_RECEIVED")
               (record-balance account cb-timestamp)))))

(defmethod create_account ((sim simulation) timestamp account_id)
  (process-cashbacks sim timestamp)
  (when (gethash account_id (sim-accounts sim))
    (return-from create_account :false))
  (setf (gethash account_id (sim-accounts sim))
        (make-account account_id timestamp))
  t)

(defmethod deposit ((sim simulation) timestamp account_id amount)
  (process-cashbacks sim timestamp)
  (let ((account (gethash account_id (sim-accounts sim))))
    (unless account
      (return-from deposit nil))
    (let ((result (deposit-account account amount)))
      (record-balance account timestamp)
      result)))

(defmethod transfer ((sim simulation) timestamp source_account_id
                     target_account_id amount)
  (process-cashbacks sim timestamp)
  (let ((source (gethash source_account_id (sim-accounts sim)))
        (target (gethash target_account_id (sim-accounts sim))))
    (when (or (null source) (null target)
              (string= source_account_id target_account_id))
      (return-from transfer nil))
    (unless (eq (withdraw-account source amount) t)
      (return-from transfer nil))
    (deposit-account target amount)
    (record-balance source timestamp)
    (record-balance target timestamp)
    (account-balance source)))

(defmethod top_spenders ((sim simulation) timestamp n)
  (process-cashbacks sim timestamp)
  (let ((ids nil))
    (maphash (lambda (id account)
               (declare (ignore account))
               (push id ids))
             (sim-accounts sim))
    (setf ids
          (sort ids
                (lambda (a b)
                  (let ((oa (account-outgoing (gethash a (sim-accounts sim))))
                        (ob (account-outgoing (gethash b (sim-accounts sim)))))
                    (cond
                      ((> oa ob) t)
                      ((< oa ob) nil)
                      (t (string< a b)))))))
    (let ((count (min n (length ids))))
      (coerce
       (loop for id in ids
             for i from 0 below count
             collect (format nil "~a(~a)" id
                             (account-outgoing (gethash id (sim-accounts sim)))))
       'vector))))

(defmethod pay ((sim simulation) timestamp account_id amount)
  (process-cashbacks sim timestamp)
  (let ((account (gethash account_id (sim-accounts sim))))
    (unless account
      (return-from pay nil))
    (unless (eq (withdraw-account account amount) t)
      (return-from pay nil))
    (incf (sim-payment-counter sim))
    (let ((payment-id (format nil "payment~a" (sim-payment-counter sim)))
          (cashback (truncate (* amount 2) 100)))
      (setf (gethash payment-id (account-payments account)) "IN_PROGRESS")
      (record-balance account timestamp)
      (setf (sim-pending sim)
            (append (sim-pending sim)
                    (list (list (+ timestamp *cashback-delay*)
                                account_id cashback payment-id))))
      payment-id)))

(defmethod get_payment_status ((sim simulation) timestamp account_id payment)
  (process-cashbacks sim timestamp)
  (let ((account (gethash account_id (sim-accounts sim))))
    (unless account
      (return-from get_payment_status nil))
    (gethash payment (account-payments account))))

(defmethod merge_accounts ((sim simulation) timestamp account_id_1 account_id_2)
  (process-cashbacks sim timestamp)
  (when (string= account_id_1 account_id_2)
    (return-from merge_accounts :false))
  (let ((account1 (gethash account_id_1 (sim-accounts sim)))
        (account2 (gethash account_id_2 (sim-accounts sim))))
    (when (or (null account1) (null account2))
      (return-from merge_accounts :false))
    (incf (account-balance account1) (account-balance account2))
    (incf (account-outgoing account1) (account-outgoing account2))
    (maphash (lambda (pid status)
               (setf (gethash pid (account-payments account1)) status))
             (account-payments account2))
    (setf (account-balance-history account1)
          (sort (append (account-balance-history account1)
                        (account-balance-history account2))
                #'< :key #'car))
    (setf (account-created-at account1)
          (min (account-created-at account1) (account-created-at account2)))
    (record-balance account1 timestamp)
    (setf (sim-pending sim)
          (mapcar (lambda (row)
                    (if (string= (second row) account_id_2)
                        (list (first row) account_id_1 (third row) (fourth row))
                        row))
                  (sim-pending sim)))
    (remhash account_id_2 (sim-accounts sim))
    t))

(defmethod get_balance ((sim simulation) timestamp account_id time_at)
  (process-cashbacks sim timestamp)
  (let ((account (gethash account_id (sim-accounts sim))))
    (unless account
      (return-from get_balance nil))
    (get-balance-at account time_at)))
